# Copyright (c) 2021 AccelByte Inc. All Rights Reserved.
# This is licensed software from AccelByte Inc, for limitations
# and restrictions contact your company contract manager.

FROM golang:1.23.0-alpine

ENV PATH="${GOPATH}/bin:${PATH}"

RUN apk add yarn git

ENTRYPOINT []
