// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.9
// source: session-manager.proto

package manager

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SessionManager_OnSessionCreated_FullMethodName = "/accelbyte.session.manager.SessionManager/OnSessionCreated"
	SessionManager_OnSessionUpdated_FullMethodName = "/accelbyte.session.manager.SessionManager/OnSessionUpdated"
	SessionManager_OnSessionDeleted_FullMethodName = "/accelbyte.session.manager.SessionManager/OnSessionDeleted"
	SessionManager_OnPartyCreated_FullMethodName   = "/accelbyte.session.manager.SessionManager/OnPartyCreated"
	SessionManager_OnPartyUpdated_FullMethodName   = "/accelbyte.session.manager.SessionManager/OnPartyUpdated"
	SessionManager_OnPartyDeleted_FullMethodName   = "/accelbyte.session.manager.SessionManager/OnPartyDeleted"
)

// SessionManagerClient is the client API for SessionManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SessionManagerClient interface {
	OnSessionCreated(ctx context.Context, in *SessionCreatedRequest, opts ...grpc.CallOption) (*SessionResponse, error)
	OnSessionUpdated(ctx context.Context, in *SessionUpdatedRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	OnSessionDeleted(ctx context.Context, in *SessionDeletedRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	OnPartyCreated(ctx context.Context, in *PartyCreatedRequest, opts ...grpc.CallOption) (*PartyResponse, error)
	OnPartyUpdated(ctx context.Context, in *PartyUpdatedRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	OnPartyDeleted(ctx context.Context, in *PartyDeletedRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type sessionManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewSessionManagerClient(cc grpc.ClientConnInterface) SessionManagerClient {
	return &sessionManagerClient{cc}
}

func (c *sessionManagerClient) OnSessionCreated(ctx context.Context, in *SessionCreatedRequest, opts ...grpc.CallOption) (*SessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionResponse)
	err := c.cc.Invoke(ctx, SessionManager_OnSessionCreated_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionManagerClient) OnSessionUpdated(ctx context.Context, in *SessionUpdatedRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SessionManager_OnSessionUpdated_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionManagerClient) OnSessionDeleted(ctx context.Context, in *SessionDeletedRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SessionManager_OnSessionDeleted_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionManagerClient) OnPartyCreated(ctx context.Context, in *PartyCreatedRequest, opts ...grpc.CallOption) (*PartyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PartyResponse)
	err := c.cc.Invoke(ctx, SessionManager_OnPartyCreated_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionManagerClient) OnPartyUpdated(ctx context.Context, in *PartyUpdatedRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SessionManager_OnPartyUpdated_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionManagerClient) OnPartyDeleted(ctx context.Context, in *PartyDeletedRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SessionManager_OnPartyDeleted_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SessionManagerServer is the server API for SessionManager service.
// All implementations should embed UnimplementedSessionManagerServer
// for forward compatibility.
type SessionManagerServer interface {
	OnSessionCreated(context.Context, *SessionCreatedRequest) (*SessionResponse, error)
	OnSessionUpdated(context.Context, *SessionUpdatedRequest) (*emptypb.Empty, error)
	OnSessionDeleted(context.Context, *SessionDeletedRequest) (*emptypb.Empty, error)
	OnPartyCreated(context.Context, *PartyCreatedRequest) (*PartyResponse, error)
	OnPartyUpdated(context.Context, *PartyUpdatedRequest) (*emptypb.Empty, error)
	OnPartyDeleted(context.Context, *PartyDeletedRequest) (*emptypb.Empty, error)
}

// UnimplementedSessionManagerServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSessionManagerServer struct{}

func (UnimplementedSessionManagerServer) OnSessionCreated(context.Context, *SessionCreatedRequest) (*SessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnSessionCreated not implemented")
}
func (UnimplementedSessionManagerServer) OnSessionUpdated(context.Context, *SessionUpdatedRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnSessionUpdated not implemented")
}
func (UnimplementedSessionManagerServer) OnSessionDeleted(context.Context, *SessionDeletedRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnSessionDeleted not implemented")
}
func (UnimplementedSessionManagerServer) OnPartyCreated(context.Context, *PartyCreatedRequest) (*PartyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnPartyCreated not implemented")
}
func (UnimplementedSessionManagerServer) OnPartyUpdated(context.Context, *PartyUpdatedRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnPartyUpdated not implemented")
}
func (UnimplementedSessionManagerServer) OnPartyDeleted(context.Context, *PartyDeletedRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnPartyDeleted not implemented")
}
func (UnimplementedSessionManagerServer) testEmbeddedByValue() {}

// UnsafeSessionManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SessionManagerServer will
// result in compilation errors.
type UnsafeSessionManagerServer interface {
	mustEmbedUnimplementedSessionManagerServer()
}

func RegisterSessionManagerServer(s grpc.ServiceRegistrar, srv SessionManagerServer) {
	// If the following call pancis, it indicates UnimplementedSessionManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SessionManager_ServiceDesc, srv)
}

func _SessionManager_OnSessionCreated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionCreatedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagerServer).OnSessionCreated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionManager_OnSessionCreated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagerServer).OnSessionCreated(ctx, req.(*SessionCreatedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionManager_OnSessionUpdated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionUpdatedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagerServer).OnSessionUpdated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionManager_OnSessionUpdated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagerServer).OnSessionUpdated(ctx, req.(*SessionUpdatedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionManager_OnSessionDeleted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionDeletedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagerServer).OnSessionDeleted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionManager_OnSessionDeleted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagerServer).OnSessionDeleted(ctx, req.(*SessionDeletedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionManager_OnPartyCreated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartyCreatedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagerServer).OnPartyCreated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionManager_OnPartyCreated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagerServer).OnPartyCreated(ctx, req.(*PartyCreatedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionManager_OnPartyUpdated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartyUpdatedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagerServer).OnPartyUpdated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionManager_OnPartyUpdated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagerServer).OnPartyUpdated(ctx, req.(*PartyUpdatedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionManager_OnPartyDeleted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartyDeletedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagerServer).OnPartyDeleted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionManager_OnPartyDeleted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagerServer).OnPartyDeleted(ctx, req.(*PartyDeletedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SessionManager_ServiceDesc is the grpc.ServiceDesc for SessionManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SessionManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accelbyte.session.manager.SessionManager",
	HandlerType: (*SessionManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnSessionCreated",
			Handler:    _SessionManager_OnSessionCreated_Handler,
		},
		{
			MethodName: "OnSessionUpdated",
			Handler:    _SessionManager_OnSessionUpdated_Handler,
		},
		{
			MethodName: "OnSessionDeleted",
			Handler:    _SessionManager_OnSessionDeleted_Handler,
		},
		{
			MethodName: "OnPartyCreated",
			Handler:    _SessionManager_OnPartyCreated_Handler,
		},
		{
			MethodName: "OnPartyUpdated",
			Handler:    _SessionManager_OnPartyUpdated_Handler,
		},
		{
			MethodName: "OnPartyDeleted",
			Handler:    _SessionManager_OnPartyDeleted_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "session-manager.proto",
}
