// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.9
// source: session-manager.proto

package manager

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Action int32

const (
	Action_None                    Action = 0
	Action_SessionCreated          Action = 1
	Action_SessionDeleted          Action = 2
	Action_SessionUserInvited      Action = 4
	Action_SessionUserRejected     Action = 8
	Action_SessionUserKicked       Action = 16
	Action_SessionUserJoined       Action = 32
	Action_SessionMembersChanged   Action = 64
	Action_SessionUpdated          Action = 128
	Action_SessionInviteTimeout    Action = 256
	Action_SessionInviteCancelled  Action = 512
	Action_DSStatusChanged         Action = 1024
	Action_SessionSync             Action = 2048
	Action_SessionStorageUpdated   Action = 4096
	Action_SessionUserLeave        Action = 8192
	Action_SessionUserConnected    Action = 16384
	Action_SessionUserDisconnected Action = 32768
	Action_SessionUserDropped      Action = 65536
	Action_SessionLeaderPromoted   Action = 131072
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0:      "None",
		1:      "SessionCreated",
		2:      "SessionDeleted",
		4:      "SessionUserInvited",
		8:      "SessionUserRejected",
		16:     "SessionUserKicked",
		32:     "SessionUserJoined",
		64:     "SessionMembersChanged",
		128:    "SessionUpdated",
		256:    "SessionInviteTimeout",
		512:    "SessionInviteCancelled",
		1024:   "DSStatusChanged",
		2048:   "SessionSync",
		4096:   "SessionStorageUpdated",
		8192:   "SessionUserLeave",
		16384:  "SessionUserConnected",
		32768:  "SessionUserDisconnected",
		65536:  "SessionUserDropped",
		131072: "SessionLeaderPromoted",
	}
	Action_value = map[string]int32{
		"None":                    0,
		"SessionCreated":          1,
		"SessionDeleted":          2,
		"SessionUserInvited":      4,
		"SessionUserRejected":     8,
		"SessionUserKicked":       16,
		"SessionUserJoined":       32,
		"SessionMembersChanged":   64,
		"SessionUpdated":          128,
		"SessionInviteTimeout":    256,
		"SessionInviteCancelled":  512,
		"DSStatusChanged":         1024,
		"SessionSync":             2048,
		"SessionStorageUpdated":   4096,
		"SessionUserLeave":        8192,
		"SessionUserConnected":    16384,
		"SessionUserDisconnected": 32768,
		"SessionUserDropped":      65536,
		"SessionLeaderPromoted":   131072,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_session_manager_proto_enumTypes[0].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_session_manager_proto_enumTypes[0]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_session_manager_proto_rawDescGZIP(), []int{0}
}

type SessionCreatedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *GameSession           `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionCreatedRequest) Reset() {
	*x = SessionCreatedRequest{}
	mi := &file_session_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionCreatedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionCreatedRequest) ProtoMessage() {}

func (x *SessionCreatedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionCreatedRequest.ProtoReflect.Descriptor instead.
func (*SessionCreatedRequest) Descriptor() ([]byte, []int) {
	return file_session_manager_proto_rawDescGZIP(), []int{0}
}

func (x *SessionCreatedRequest) GetSession() *GameSession {
	if x != nil {
		return x.Session
	}
	return nil
}

type SessionUpdatedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionOld    *GameSession           `protobuf:"bytes,1,opt,name=session_old,json=sessionOld,proto3" json:"session_old,omitempty"`
	SessionNew    *GameSession           `protobuf:"bytes,2,opt,name=session_new,json=sessionNew,proto3" json:"session_new,omitempty"`
	Action        Action                 `protobuf:"varint,3,opt,name=action,proto3,enum=accelbyte.session.manager.Action" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionUpdatedRequest) Reset() {
	*x = SessionUpdatedRequest{}
	mi := &file_session_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionUpdatedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionUpdatedRequest) ProtoMessage() {}

func (x *SessionUpdatedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionUpdatedRequest.ProtoReflect.Descriptor instead.
func (*SessionUpdatedRequest) Descriptor() ([]byte, []int) {
	return file_session_manager_proto_rawDescGZIP(), []int{1}
}

func (x *SessionUpdatedRequest) GetSessionOld() *GameSession {
	if x != nil {
		return x.SessionOld
	}
	return nil
}

func (x *SessionUpdatedRequest) GetSessionNew() *GameSession {
	if x != nil {
		return x.SessionNew
	}
	return nil
}

func (x *SessionUpdatedRequest) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_None
}

type SessionDeletedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *GameSession           `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionDeletedRequest) Reset() {
	*x = SessionDeletedRequest{}
	mi := &file_session_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionDeletedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionDeletedRequest) ProtoMessage() {}

func (x *SessionDeletedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionDeletedRequest.ProtoReflect.Descriptor instead.
func (*SessionDeletedRequest) Descriptor() ([]byte, []int) {
	return file_session_manager_proto_rawDescGZIP(), []int{2}
}

func (x *SessionDeletedRequest) GetSession() *GameSession {
	if x != nil {
		return x.Session
	}
	return nil
}

type SessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *GameSession           `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionResponse) Reset() {
	*x = SessionResponse{}
	mi := &file_session_manager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionResponse) ProtoMessage() {}

func (x *SessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_session_manager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionResponse.ProtoReflect.Descriptor instead.
func (*SessionResponse) Descriptor() ([]byte, []int) {
	return file_session_manager_proto_rawDescGZIP(), []int{3}
}

func (x *SessionResponse) GetSession() *GameSession {
	if x != nil {
		return x.Session
	}
	return nil
}

type Configuration struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Attributes                *structpb.Struct       `protobuf:"bytes,1,opt,name=attributes,proto3" json:"attributes,omitempty"`
	AutoJoin                  bool                   `protobuf:"varint,2,opt,name=auto_join,json=autoJoin,proto3" json:"auto_join,omitempty"`
	InactiveTimeout           int32                  `protobuf:"varint,3,opt,name=inactive_timeout,json=inactiveTimeout,proto3" json:"inactive_timeout,omitempty"`
	InviteTimeout             int32                  `protobuf:"varint,4,opt,name=invite_timeout,json=inviteTimeout,proto3" json:"invite_timeout,omitempty"`
	Joinability               string                 `protobuf:"bytes,5,opt,name=joinability,proto3" json:"joinability,omitempty"`
	LeaderElectionGracePeriod int32                  `protobuf:"varint,6,opt,name=leader_election_grace_period,json=leaderElectionGracePeriod,proto3" json:"leader_election_grace_period,omitempty"`
	MaxPlayers                int32                  `protobuf:"varint,7,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	MinPlayers                int32                  `protobuf:"varint,8,opt,name=min_players,json=minPlayers,proto3" json:"min_players,omitempty"`
	Persistent                bool                   `protobuf:"varint,9,opt,name=persistent,proto3" json:"persistent,omitempty"`
	TextChat                  bool                   `protobuf:"varint,10,opt,name=text_chat,json=textChat,proto3" json:"text_chat,omitempty"`
	DisableResendInvite       bool                   `protobuf:"varint,11,opt,name=disable_resend_invite,json=disableResendInvite,proto3" json:"disable_resend_invite,omitempty"`
	Type                      string                 `protobuf:"bytes,12,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *Configuration) Reset() {
	*x = Configuration{}
	mi := &file_session_manager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Configuration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configuration) ProtoMessage() {}

func (x *Configuration) ProtoReflect() protoreflect.Message {
	mi := &file_session_manager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Configuration.ProtoReflect.Descriptor instead.
func (*Configuration) Descriptor() ([]byte, []int) {
	return file_session_manager_proto_rawDescGZIP(), []int{4}
}

func (x *Configuration) GetAttributes() *structpb.Struct {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Configuration) GetAutoJoin() bool {
	if x != nil {
		return x.AutoJoin
	}
	return false
}

func (x *Configuration) GetInactiveTimeout() int32 {
	if x != nil {
		return x.InactiveTimeout
	}
	return 0
}

func (x *Configuration) GetInviteTimeout() int32 {
	if x != nil {
		return x.InviteTimeout
	}
	return 0
}

func (x *Configuration) GetJoinability() string {
	if x != nil {
		return x.Joinability
	}
	return ""
}

func (x *Configuration) GetLeaderElectionGracePeriod() int32 {
	if x != nil {
		return x.LeaderElectionGracePeriod
	}
	return 0
}

func (x *Configuration) GetMaxPlayers() int32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *Configuration) GetMinPlayers() int32 {
	if x != nil {
		return x.MinPlayers
	}
	return 0
}

func (x *Configuration) GetPersistent() bool {
	if x != nil {
		return x.Persistent
	}
	return false
}

func (x *Configuration) GetTextChat() bool {
	if x != nil {
		return x.TextChat
	}
	return false
}

func (x *Configuration) GetDisableResendInvite() bool {
	if x != nil {
		return x.DisableResendInvite
	}
	return false
}

func (x *Configuration) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type User struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	StatusV2       string                 `protobuf:"bytes,3,opt,name=status_v2,json=statusV2,proto3" json:"status_v2,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	PlatformId     string                 `protobuf:"bytes,5,opt,name=platform_id,json=platformId,proto3" json:"platform_id,omitempty"`
	PlatformUserId string                 `protobuf:"bytes,6,opt,name=platform_user_id,json=platformUserId,proto3" json:"platform_user_id,omitempty"`
	PreviousStatus string                 `protobuf:"bytes,7,opt,name=previous_status,json=previousStatus,proto3" json:"previous_status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_session_manager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_session_manager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_session_manager_proto_rawDescGZIP(), []int{5}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *User) GetStatusV2() string {
	if x != nil {
		return x.StatusV2
	}
	return ""
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *User) GetPlatformId() string {
	if x != nil {
		return x.PlatformId
	}
	return ""
}

func (x *User) GetPlatformUserId() string {
	if x != nil {
		return x.PlatformUserId
	}
	return ""
}

func (x *User) GetPreviousStatus() string {
	if x != nil {
		return x.PreviousStatus
	}
	return ""
}

type BaseSession struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IsActive          bool                   `protobuf:"varint,1,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	IsFull            bool                   `protobuf:"varint,2,opt,name=is_full,json=isFull,proto3" json:"is_full,omitempty"`
	Version           int32                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Id                string                 `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	Namespace         string                 `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`
	CreatedBy         string                 `protobuf:"bytes,6,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	ConfigurationName string                 `protobuf:"bytes,7,opt,name=configuration_name,json=configurationName,proto3" json:"configuration_name,omitempty"`
	LeaderId          string                 `protobuf:"bytes,8,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiredAt         *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Attributes        *structpb.Struct       `protobuf:"bytes,12,opt,name=attributes,proto3" json:"attributes,omitempty"`
	Storages          *structpb.Struct       `protobuf:"bytes,13,opt,name=storages,proto3" json:"storages,omitempty"`
	Configuration     *Configuration         `protobuf:"bytes,14,opt,name=configuration,proto3" json:"configuration,omitempty"`
	Members           []*User                `protobuf:"bytes,15,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BaseSession) Reset() {
	*x = BaseSession{}
	mi := &file_session_manager_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseSession) ProtoMessage() {}

func (x *BaseSession) ProtoReflect() protoreflect.Message {
	mi := &file_session_manager_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseSession.ProtoReflect.Descriptor instead.
func (*BaseSession) Descriptor() ([]byte, []int) {
	return file_session_manager_proto_rawDescGZIP(), []int{6}
}

func (x *BaseSession) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *BaseSession) GetIsFull() bool {
	if x != nil {
		return x.IsFull
	}
	return false
}

func (x *BaseSession) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *BaseSession) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BaseSession) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *BaseSession) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *BaseSession) GetConfigurationName() string {
	if x != nil {
		return x.ConfigurationName
	}
	return ""
}

func (x *BaseSession) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *BaseSession) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *BaseSession) GetExpiredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiredAt
	}
	return nil
}

func (x *BaseSession) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *BaseSession) GetAttributes() *structpb.Struct {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *BaseSession) GetStorages() *structpb.Struct {
	if x != nil {
		return x.Storages
	}
	return nil
}

func (x *BaseSession) GetConfiguration() *Configuration {
	if x != nil {
		return x.Configuration
	}
	return nil
}

func (x *BaseSession) GetMembers() []*User {
	if x != nil {
		return x.Members
	}
	return nil
}

type DSInformation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestedAt   *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	StatusV2      string                 `protobuf:"bytes,3,opt,name=status_v2,json=statusV2,proto3" json:"status_v2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DSInformation) Reset() {
	*x = DSInformation{}
	mi := &file_session_manager_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DSInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DSInformation) ProtoMessage() {}

func (x *DSInformation) ProtoReflect() protoreflect.Message {
	mi := &file_session_manager_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DSInformation.ProtoReflect.Descriptor instead.
func (*DSInformation) Descriptor() ([]byte, []int) {
	return file_session_manager_proto_rawDescGZIP(), []int{7}
}

func (x *DSInformation) GetRequestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RequestedAt
	}
	return nil
}

func (x *DSInformation) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DSInformation) GetStatusV2() string {
	if x != nil {
		return x.StatusV2
	}
	return ""
}

type PartyMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartyId       string                 `protobuf:"bytes,1,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	UserIds       []string               `protobuf:"bytes,2,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartyMember) Reset() {
	*x = PartyMember{}
	mi := &file_session_manager_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartyMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyMember) ProtoMessage() {}

func (x *PartyMember) ProtoReflect() protoreflect.Message {
	mi := &file_session_manager_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyMember.ProtoReflect.Descriptor instead.
func (*PartyMember) Descriptor() ([]byte, []int) {
	return file_session_manager_proto_rawDescGZIP(), []int{8}
}

func (x *PartyMember) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *PartyMember) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type Team struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	PartyMembers  []*PartyMember         `protobuf:"bytes,2,rep,name=party_members,json=partyMembers,proto3" json:"party_members,omitempty"`
	TeamId        string                 `protobuf:"bytes,3,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Team) Reset() {
	*x = Team{}
	mi := &file_session_manager_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Team) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Team) ProtoMessage() {}

func (x *Team) ProtoReflect() protoreflect.Message {
	mi := &file_session_manager_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Team.ProtoReflect.Descriptor instead.
func (*Team) Descriptor() ([]byte, []int) {
	return file_session_manager_proto_rawDescGZIP(), []int{9}
}

func (x *Team) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *Team) GetPartyMembers() []*PartyMember {
	if x != nil {
		return x.PartyMembers
	}
	return nil
}

func (x *Team) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

type GameSession struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Retry            int32                  `protobuf:"varint,1,opt,name=retry,proto3" json:"retry,omitempty"`
	ProcessingTime   int64                  `protobuf:"varint,2,opt,name=processing_time,json=processingTime,proto3" json:"processing_time,omitempty"`
	MatchPool        string                 `protobuf:"bytes,3,opt,name=match_pool,json=matchPool,proto3" json:"match_pool,omitempty"`
	BackfillTicketId string                 `protobuf:"bytes,4,opt,name=backfill_ticket_id,json=backfillTicketId,proto3" json:"backfill_ticket_id,omitempty"`
	ServerName       string                 `protobuf:"bytes,5,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	Step             string                 `protobuf:"bytes,6,opt,name=step,proto3" json:"step,omitempty"`
	Code             string                 `protobuf:"bytes,7,opt,name=code,proto3" json:"code,omitempty"`
	TicketIds        []string               `protobuf:"bytes,8,rep,name=ticket_ids,json=ticketIds,proto3" json:"ticket_ids,omitempty"`
	DsInformation    *DSInformation         `protobuf:"bytes,9,opt,name=ds_information,json=dsInformation,proto3" json:"ds_information,omitempty"`
	Session          *BaseSession           `protobuf:"bytes,10,opt,name=session,proto3" json:"session,omitempty"`
	Teams            []*Team                `protobuf:"bytes,11,rep,name=teams,proto3" json:"teams,omitempty"`
	Secret           string                 `protobuf:"bytes,12,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GameSession) Reset() {
	*x = GameSession{}
	mi := &file_session_manager_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameSession) ProtoMessage() {}

func (x *GameSession) ProtoReflect() protoreflect.Message {
	mi := &file_session_manager_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameSession.ProtoReflect.Descriptor instead.
func (*GameSession) Descriptor() ([]byte, []int) {
	return file_session_manager_proto_rawDescGZIP(), []int{10}
}

func (x *GameSession) GetRetry() int32 {
	if x != nil {
		return x.Retry
	}
	return 0
}

func (x *GameSession) GetProcessingTime() int64 {
	if x != nil {
		return x.ProcessingTime
	}
	return 0
}

func (x *GameSession) GetMatchPool() string {
	if x != nil {
		return x.MatchPool
	}
	return ""
}

func (x *GameSession) GetBackfillTicketId() string {
	if x != nil {
		return x.BackfillTicketId
	}
	return ""
}

func (x *GameSession) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *GameSession) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *GameSession) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GameSession) GetTicketIds() []string {
	if x != nil {
		return x.TicketIds
	}
	return nil
}

func (x *GameSession) GetDsInformation() *DSInformation {
	if x != nil {
		return x.DsInformation
	}
	return nil
}

func (x *GameSession) GetSession() *BaseSession {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *GameSession) GetTeams() []*Team {
	if x != nil {
		return x.Teams
	}
	return nil
}

func (x *GameSession) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type PartySession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *BaseSession           `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartySession) Reset() {
	*x = PartySession{}
	mi := &file_session_manager_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartySession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartySession) ProtoMessage() {}

func (x *PartySession) ProtoReflect() protoreflect.Message {
	mi := &file_session_manager_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartySession.ProtoReflect.Descriptor instead.
func (*PartySession) Descriptor() ([]byte, []int) {
	return file_session_manager_proto_rawDescGZIP(), []int{11}
}

func (x *PartySession) GetSession() *BaseSession {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *PartySession) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type PartyCreatedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *PartySession          `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartyCreatedRequest) Reset() {
	*x = PartyCreatedRequest{}
	mi := &file_session_manager_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartyCreatedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyCreatedRequest) ProtoMessage() {}

func (x *PartyCreatedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_manager_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyCreatedRequest.ProtoReflect.Descriptor instead.
func (*PartyCreatedRequest) Descriptor() ([]byte, []int) {
	return file_session_manager_proto_rawDescGZIP(), []int{12}
}

func (x *PartyCreatedRequest) GetSession() *PartySession {
	if x != nil {
		return x.Session
	}
	return nil
}

type PartyUpdatedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionOld    *PartySession          `protobuf:"bytes,1,opt,name=session_old,json=sessionOld,proto3" json:"session_old,omitempty"`
	SessionNew    *PartySession          `protobuf:"bytes,2,opt,name=session_new,json=sessionNew,proto3" json:"session_new,omitempty"`
	Action        Action                 `protobuf:"varint,3,opt,name=action,proto3,enum=accelbyte.session.manager.Action" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartyUpdatedRequest) Reset() {
	*x = PartyUpdatedRequest{}
	mi := &file_session_manager_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartyUpdatedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyUpdatedRequest) ProtoMessage() {}

func (x *PartyUpdatedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_manager_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyUpdatedRequest.ProtoReflect.Descriptor instead.
func (*PartyUpdatedRequest) Descriptor() ([]byte, []int) {
	return file_session_manager_proto_rawDescGZIP(), []int{13}
}

func (x *PartyUpdatedRequest) GetSessionOld() *PartySession {
	if x != nil {
		return x.SessionOld
	}
	return nil
}

func (x *PartyUpdatedRequest) GetSessionNew() *PartySession {
	if x != nil {
		return x.SessionNew
	}
	return nil
}

func (x *PartyUpdatedRequest) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_None
}

type PartyDeletedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *PartySession          `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartyDeletedRequest) Reset() {
	*x = PartyDeletedRequest{}
	mi := &file_session_manager_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartyDeletedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyDeletedRequest) ProtoMessage() {}

func (x *PartyDeletedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_manager_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyDeletedRequest.ProtoReflect.Descriptor instead.
func (*PartyDeletedRequest) Descriptor() ([]byte, []int) {
	return file_session_manager_proto_rawDescGZIP(), []int{14}
}

func (x *PartyDeletedRequest) GetSession() *PartySession {
	if x != nil {
		return x.Session
	}
	return nil
}

type PartyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *PartySession          `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartyResponse) Reset() {
	*x = PartyResponse{}
	mi := &file_session_manager_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyResponse) ProtoMessage() {}

func (x *PartyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_session_manager_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyResponse.ProtoReflect.Descriptor instead.
func (*PartyResponse) Descriptor() ([]byte, []int) {
	return file_session_manager_proto_rawDescGZIP(), []int{15}
}

func (x *PartyResponse) GetSession() *PartySession {
	if x != nil {
		return x.Session
	}
	return nil
}

var File_session_manager_proto protoreflect.FileDescriptor

const file_session_manager_proto_rawDesc = "" +
	"\n" +
	"\x15session-manager.proto\x12\x19accelbyte.session.manager\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1bgoogle/protobuf/empty.proto\"Y\n" +
	"\x15SessionCreatedRequest\x12@\n" +
	"\asession\x18\x01 \x01(\v2&.accelbyte.session.manager.GameSessionR\asession\"\xe4\x01\n" +
	"\x15SessionUpdatedRequest\x12G\n" +
	"\vsession_old\x18\x01 \x01(\v2&.accelbyte.session.manager.GameSessionR\n" +
	"sessionOld\x12G\n" +
	"\vsession_new\x18\x02 \x01(\v2&.accelbyte.session.manager.GameSessionR\n" +
	"sessionNew\x129\n" +
	"\x06action\x18\x03 \x01(\x0e2!.accelbyte.session.manager.ActionR\x06action\"Y\n" +
	"\x15SessionDeletedRequest\x12@\n" +
	"\asession\x18\x01 \x01(\v2&.accelbyte.session.manager.GameSessionR\asession\"S\n" +
	"\x0fSessionResponse\x12@\n" +
	"\asession\x18\x01 \x01(\v2&.accelbyte.session.manager.GameSessionR\asession\"\xe1\x03\n" +
	"\rConfiguration\x127\n" +
	"\n" +
	"attributes\x18\x01 \x01(\v2\x17.google.protobuf.StructR\n" +
	"attributes\x12\x1b\n" +
	"\tauto_join\x18\x02 \x01(\bR\bautoJoin\x12)\n" +
	"\x10inactive_timeout\x18\x03 \x01(\x05R\x0finactiveTimeout\x12%\n" +
	"\x0einvite_timeout\x18\x04 \x01(\x05R\rinviteTimeout\x12 \n" +
	"\vjoinability\x18\x05 \x01(\tR\vjoinability\x12?\n" +
	"\x1cleader_election_grace_period\x18\x06 \x01(\x05R\x19leaderElectionGracePeriod\x12\x1f\n" +
	"\vmax_players\x18\a \x01(\x05R\n" +
	"maxPlayers\x12\x1f\n" +
	"\vmin_players\x18\b \x01(\x05R\n" +
	"minPlayers\x12\x1e\n" +
	"\n" +
	"persistent\x18\t \x01(\bR\n" +
	"persistent\x12\x1b\n" +
	"\ttext_chat\x18\n" +
	" \x01(\bR\btextChat\x122\n" +
	"\x15disable_resend_invite\x18\v \x01(\bR\x13disableResendInvite\x12\x12\n" +
	"\x04type\x18\f \x01(\tR\x04type\"\xfa\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1b\n" +
	"\tstatus_v2\x18\x03 \x01(\tR\bstatusV2\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vplatform_id\x18\x05 \x01(\tR\n" +
	"platformId\x12(\n" +
	"\x10platform_user_id\x18\x06 \x01(\tR\x0eplatformUserId\x12'\n" +
	"\x0fprevious_status\x18\a \x01(\tR\x0epreviousStatus\"\xa0\x05\n" +
	"\vBaseSession\x12\x1b\n" +
	"\tis_active\x18\x01 \x01(\bR\bisActive\x12\x17\n" +
	"\ais_full\x18\x02 \x01(\bR\x06isFull\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x05R\aversion\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\x12\x1d\n" +
	"\n" +
	"created_by\x18\x06 \x01(\tR\tcreatedBy\x12-\n" +
	"\x12configuration_name\x18\a \x01(\tR\x11configurationName\x12\x1b\n" +
	"\tleader_id\x18\b \x01(\tR\bleaderId\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"expired_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\texpiredAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x127\n" +
	"\n" +
	"attributes\x18\f \x01(\v2\x17.google.protobuf.StructR\n" +
	"attributes\x123\n" +
	"\bstorages\x18\r \x01(\v2\x17.google.protobuf.StructR\bstorages\x12N\n" +
	"\rconfiguration\x18\x0e \x01(\v2(.accelbyte.session.manager.ConfigurationR\rconfiguration\x129\n" +
	"\amembers\x18\x0f \x03(\v2\x1f.accelbyte.session.manager.UserR\amembers\"\x83\x01\n" +
	"\rDSInformation\x12=\n" +
	"\frequested_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\vrequestedAt\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1b\n" +
	"\tstatus_v2\x18\x03 \x01(\tR\bstatusV2\"C\n" +
	"\vPartyMember\x12\x19\n" +
	"\bparty_id\x18\x01 \x01(\tR\apartyId\x12\x19\n" +
	"\buser_ids\x18\x02 \x03(\tR\auserIds\"\x87\x01\n" +
	"\x04Team\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\x12K\n" +
	"\rparty_members\x18\x02 \x03(\v2&.accelbyte.session.manager.PartyMemberR\fpartyMembers\x12\x17\n" +
	"\ateam_id\x18\x03 \x01(\tR\x06teamId\"\xe3\x03\n" +
	"\vGameSession\x12\x14\n" +
	"\x05retry\x18\x01 \x01(\x05R\x05retry\x12'\n" +
	"\x0fprocessing_time\x18\x02 \x01(\x03R\x0eprocessingTime\x12\x1d\n" +
	"\n" +
	"match_pool\x18\x03 \x01(\tR\tmatchPool\x12,\n" +
	"\x12backfill_ticket_id\x18\x04 \x01(\tR\x10backfillTicketId\x12\x1f\n" +
	"\vserver_name\x18\x05 \x01(\tR\n" +
	"serverName\x12\x12\n" +
	"\x04step\x18\x06 \x01(\tR\x04step\x12\x12\n" +
	"\x04code\x18\a \x01(\tR\x04code\x12\x1d\n" +
	"\n" +
	"ticket_ids\x18\b \x03(\tR\tticketIds\x12O\n" +
	"\x0eds_information\x18\t \x01(\v2(.accelbyte.session.manager.DSInformationR\rdsInformation\x12@\n" +
	"\asession\x18\n" +
	" \x01(\v2&.accelbyte.session.manager.BaseSessionR\asession\x125\n" +
	"\x05teams\x18\v \x03(\v2\x1f.accelbyte.session.manager.TeamR\x05teams\x12\x16\n" +
	"\x06secret\x18\f \x01(\tR\x06secret\"d\n" +
	"\fPartySession\x12@\n" +
	"\asession\x18\x01 \x01(\v2&.accelbyte.session.manager.BaseSessionR\asession\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"X\n" +
	"\x13PartyCreatedRequest\x12A\n" +
	"\asession\x18\x01 \x01(\v2'.accelbyte.session.manager.PartySessionR\asession\"\xe4\x01\n" +
	"\x13PartyUpdatedRequest\x12H\n" +
	"\vsession_old\x18\x01 \x01(\v2'.accelbyte.session.manager.PartySessionR\n" +
	"sessionOld\x12H\n" +
	"\vsession_new\x18\x02 \x01(\v2'.accelbyte.session.manager.PartySessionR\n" +
	"sessionNew\x129\n" +
	"\x06action\x18\x03 \x01(\x0e2!.accelbyte.session.manager.ActionR\x06action\"X\n" +
	"\x13PartyDeletedRequest\x12A\n" +
	"\asession\x18\x01 \x01(\v2'.accelbyte.session.manager.PartySessionR\asession\"R\n" +
	"\rPartyResponse\x12A\n" +
	"\asession\x18\x01 \x01(\v2'.accelbyte.session.manager.PartySessionR\asession*\xce\x03\n" +
	"\x06Action\x12\b\n" +
	"\x04None\x10\x00\x12\x12\n" +
	"\x0eSessionCreated\x10\x01\x12\x12\n" +
	"\x0eSessionDeleted\x10\x02\x12\x16\n" +
	"\x12SessionUserInvited\x10\x04\x12\x17\n" +
	"\x13SessionUserRejected\x10\b\x12\x15\n" +
	"\x11SessionUserKicked\x10\x10\x12\x15\n" +
	"\x11SessionUserJoined\x10 \x12\x19\n" +
	"\x15SessionMembersChanged\x10@\x12\x13\n" +
	"\x0eSessionUpdated\x10\x80\x01\x12\x19\n" +
	"\x14SessionInviteTimeout\x10\x80\x02\x12\x1b\n" +
	"\x16SessionInviteCancelled\x10\x80\x04\x12\x14\n" +
	"\x0fDSStatusChanged\x10\x80\b\x12\x10\n" +
	"\vSessionSync\x10\x80\x10\x12\x1a\n" +
	"\x15SessionStorageUpdated\x10\x80 \x12\x15\n" +
	"\x10SessionUserLeave\x10\x80@\x12\x1a\n" +
	"\x14SessionUserConnected\x10\x80\x80\x01\x12\x1d\n" +
	"\x17SessionUserDisconnected\x10\x80\x80\x02\x12\x18\n" +
	"\x12SessionUserDropped\x10\x80\x80\x04\x12\x1b\n" +
	"\x15SessionLeaderPromoted\x10\x80\x80\b2\xde\x04\n" +
	"\x0eSessionManager\x12p\n" +
	"\x10OnSessionCreated\x120.accelbyte.session.manager.SessionCreatedRequest\x1a*.accelbyte.session.manager.SessionResponse\x12\\\n" +
	"\x10OnSessionUpdated\x120.accelbyte.session.manager.SessionUpdatedRequest\x1a\x16.google.protobuf.Empty\x12\\\n" +
	"\x10OnSessionDeleted\x120.accelbyte.session.manager.SessionDeletedRequest\x1a\x16.google.protobuf.Empty\x12j\n" +
	"\x0eOnPartyCreated\x12..accelbyte.session.manager.PartyCreatedRequest\x1a(.accelbyte.session.manager.PartyResponse\x12X\n" +
	"\x0eOnPartyUpdated\x12..accelbyte.session.manager.PartyUpdatedRequest\x1a\x16.google.protobuf.Empty\x12X\n" +
	"\x0eOnPartyDeleted\x12..accelbyte.session.manager.PartyDeletedRequest\x1a\x16.google.protobuf.EmptyB\\\n" +
	"\x1dnet.accelbyte.session.managerP\x01Z\x1daccelbyte.net/session/manager\xaa\x02\x19AccelByte.Session.managerb\x06proto3"

var (
	file_session_manager_proto_rawDescOnce sync.Once
	file_session_manager_proto_rawDescData []byte
)

func file_session_manager_proto_rawDescGZIP() []byte {
	file_session_manager_proto_rawDescOnce.Do(func() {
		file_session_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_session_manager_proto_rawDesc), len(file_session_manager_proto_rawDesc)))
	})
	return file_session_manager_proto_rawDescData
}

var file_session_manager_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_session_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_session_manager_proto_goTypes = []any{
	(Action)(0),                   // 0: accelbyte.session.manager.Action
	(*SessionCreatedRequest)(nil), // 1: accelbyte.session.manager.SessionCreatedRequest
	(*SessionUpdatedRequest)(nil), // 2: accelbyte.session.manager.SessionUpdatedRequest
	(*SessionDeletedRequest)(nil), // 3: accelbyte.session.manager.SessionDeletedRequest
	(*SessionResponse)(nil),       // 4: accelbyte.session.manager.SessionResponse
	(*Configuration)(nil),         // 5: accelbyte.session.manager.Configuration
	(*User)(nil),                  // 6: accelbyte.session.manager.User
	(*BaseSession)(nil),           // 7: accelbyte.session.manager.BaseSession
	(*DSInformation)(nil),         // 8: accelbyte.session.manager.DSInformation
	(*PartyMember)(nil),           // 9: accelbyte.session.manager.PartyMember
	(*Team)(nil),                  // 10: accelbyte.session.manager.Team
	(*GameSession)(nil),           // 11: accelbyte.session.manager.GameSession
	(*PartySession)(nil),          // 12: accelbyte.session.manager.PartySession
	(*PartyCreatedRequest)(nil),   // 13: accelbyte.session.manager.PartyCreatedRequest
	(*PartyUpdatedRequest)(nil),   // 14: accelbyte.session.manager.PartyUpdatedRequest
	(*PartyDeletedRequest)(nil),   // 15: accelbyte.session.manager.PartyDeletedRequest
	(*PartyResponse)(nil),         // 16: accelbyte.session.manager.PartyResponse
	(*structpb.Struct)(nil),       // 17: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 18: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 19: google.protobuf.Empty
}
var file_session_manager_proto_depIdxs = []int32{
	11, // 0: accelbyte.session.manager.SessionCreatedRequest.session:type_name -> accelbyte.session.manager.GameSession
	11, // 1: accelbyte.session.manager.SessionUpdatedRequest.session_old:type_name -> accelbyte.session.manager.GameSession
	11, // 2: accelbyte.session.manager.SessionUpdatedRequest.session_new:type_name -> accelbyte.session.manager.GameSession
	0,  // 3: accelbyte.session.manager.SessionUpdatedRequest.action:type_name -> accelbyte.session.manager.Action
	11, // 4: accelbyte.session.manager.SessionDeletedRequest.session:type_name -> accelbyte.session.manager.GameSession
	11, // 5: accelbyte.session.manager.SessionResponse.session:type_name -> accelbyte.session.manager.GameSession
	17, // 6: accelbyte.session.manager.Configuration.attributes:type_name -> google.protobuf.Struct
	18, // 7: accelbyte.session.manager.User.updated_at:type_name -> google.protobuf.Timestamp
	18, // 8: accelbyte.session.manager.BaseSession.created_at:type_name -> google.protobuf.Timestamp
	18, // 9: accelbyte.session.manager.BaseSession.expired_at:type_name -> google.protobuf.Timestamp
	18, // 10: accelbyte.session.manager.BaseSession.updated_at:type_name -> google.protobuf.Timestamp
	17, // 11: accelbyte.session.manager.BaseSession.attributes:type_name -> google.protobuf.Struct
	17, // 12: accelbyte.session.manager.BaseSession.storages:type_name -> google.protobuf.Struct
	5,  // 13: accelbyte.session.manager.BaseSession.configuration:type_name -> accelbyte.session.manager.Configuration
	6,  // 14: accelbyte.session.manager.BaseSession.members:type_name -> accelbyte.session.manager.User
	18, // 15: accelbyte.session.manager.DSInformation.requested_at:type_name -> google.protobuf.Timestamp
	9,  // 16: accelbyte.session.manager.Team.party_members:type_name -> accelbyte.session.manager.PartyMember
	8,  // 17: accelbyte.session.manager.GameSession.ds_information:type_name -> accelbyte.session.manager.DSInformation
	7,  // 18: accelbyte.session.manager.GameSession.session:type_name -> accelbyte.session.manager.BaseSession
	10, // 19: accelbyte.session.manager.GameSession.teams:type_name -> accelbyte.session.manager.Team
	7,  // 20: accelbyte.session.manager.PartySession.session:type_name -> accelbyte.session.manager.BaseSession
	12, // 21: accelbyte.session.manager.PartyCreatedRequest.session:type_name -> accelbyte.session.manager.PartySession
	12, // 22: accelbyte.session.manager.PartyUpdatedRequest.session_old:type_name -> accelbyte.session.manager.PartySession
	12, // 23: accelbyte.session.manager.PartyUpdatedRequest.session_new:type_name -> accelbyte.session.manager.PartySession
	0,  // 24: accelbyte.session.manager.PartyUpdatedRequest.action:type_name -> accelbyte.session.manager.Action
	12, // 25: accelbyte.session.manager.PartyDeletedRequest.session:type_name -> accelbyte.session.manager.PartySession
	12, // 26: accelbyte.session.manager.PartyResponse.session:type_name -> accelbyte.session.manager.PartySession
	1,  // 27: accelbyte.session.manager.SessionManager.OnSessionCreated:input_type -> accelbyte.session.manager.SessionCreatedRequest
	2,  // 28: accelbyte.session.manager.SessionManager.OnSessionUpdated:input_type -> accelbyte.session.manager.SessionUpdatedRequest
	3,  // 29: accelbyte.session.manager.SessionManager.OnSessionDeleted:input_type -> accelbyte.session.manager.SessionDeletedRequest
	13, // 30: accelbyte.session.manager.SessionManager.OnPartyCreated:input_type -> accelbyte.session.manager.PartyCreatedRequest
	14, // 31: accelbyte.session.manager.SessionManager.OnPartyUpdated:input_type -> accelbyte.session.manager.PartyUpdatedRequest
	15, // 32: accelbyte.session.manager.SessionManager.OnPartyDeleted:input_type -> accelbyte.session.manager.PartyDeletedRequest
	4,  // 33: accelbyte.session.manager.SessionManager.OnSessionCreated:output_type -> accelbyte.session.manager.SessionResponse
	19, // 34: accelbyte.session.manager.SessionManager.OnSessionUpdated:output_type -> google.protobuf.Empty
	19, // 35: accelbyte.session.manager.SessionManager.OnSessionDeleted:output_type -> google.protobuf.Empty
	16, // 36: accelbyte.session.manager.SessionManager.OnPartyCreated:output_type -> accelbyte.session.manager.PartyResponse
	19, // 37: accelbyte.session.manager.SessionManager.OnPartyUpdated:output_type -> google.protobuf.Empty
	19, // 38: accelbyte.session.manager.SessionManager.OnPartyDeleted:output_type -> google.protobuf.Empty
	33, // [33:39] is the sub-list for method output_type
	27, // [27:33] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_session_manager_proto_init() }
func file_session_manager_proto_init() {
	if File_session_manager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_session_manager_proto_rawDesc), len(file_session_manager_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_session_manager_proto_goTypes,
		DependencyIndexes: file_session_manager_proto_depIdxs,
		EnumInfos:         file_session_manager_proto_enumTypes,
		MessageInfos:      file_session_manager_proto_msgTypes,
	}.Build()
	File_session_manager_proto = out.File
	file_session_manager_proto_goTypes = nil
	file_session_manager_proto_depIdxs = nil
}
